settings:
  epoch_n: 5
  image_size: 572
  use_gpu: true

model:
  use_existing_model: true
  existing_model_filename: 'final-models/experiment-10.pt'
  final_model_filename: 'final-models/experiment-11.pt'
  experiment_info_filename: 'experiment-info/experiment-11-info.json'
  criterion: 'CrossEntropyLoss'
  optimizer:
    name: Adam
    lr: 0.000001
    weight_decay: 0.0005

dataset:
  images_directory: 'data/cells'
  train_test_split: 0.8
  batch_size: 4
  augment_data: true



